language: node_js
node_js:
- 6.0.0
branches:
  only:
  - master

install: npm install

before_script:
- git config --global user.name "KL"
- git config --global user.email "kfldev@outlook.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml
- npm install -g gulp

script: npm run build